### PR TITLE
Fix issues with increasing volume.

### PR DESCRIPTION
**Pull request by sarg**
When current `pulseaudio-control--current-sink` is either sink name or
`@DEFAULT_SINK@`, `pulseaudio-control--get-current-volume` fails, because it
only supports numerical indexes. Also `pulseaudio-control-increase-volume`
fails, because it uses current volume.

### CODE REVIEW

**Comment by flexibeast** [comment]
Thank you for your pull request!

The variable `pulseaudio-control--current-sink` variable is, as the `--` after the package name indicates, a variable used internally by the `pulseaudio-control` package - it's not something that users should be setting directly. Instead, users are supposed to 'set' it via the user-facing interactive commands `pulseaudio-control-select-sink-by-*`. That's why there's no support in the package (e.g. in `pulseaudio-control--get-current-volume`) for that variable to contain a sink name rather than a sink index.

Consequently, it's a bad idea for users to be directly setting `pulseaudio-control--current-sink`, as you have said you've done ([here](https://github.com/flexibeast/pulseaudio-control/issues/4#issuecomment-384259600)). Although it might work for you, it might not work out for other users: if they subsequently set the value of that variable to a specific sink, via the ``pulseaudio-control-select-sink-by-*` commands, the only way to resume using `@DEFAULT_SINK@` is to manually evaluate some ELisp. This is not something i feel users should have to do during routine use of the package (as distinct from, setting up the package for use).

Having said all that, i think your PR can form the core of a more complete solution, and so i've created a new branch, https://github.com/flexibeast/pulseaudio-control/tree/support-default-sink, and will merge your PR there, upon which i can then add full support for `@DEFAULT_SINK@`.

Thanks again!

**Comment by flexibeast** [comment]
i've just pushed what i believe to be a solution for this issue to the `support-default-sink` branch - can you please checkout that branch and let me know if it works for you?

**Comment by sarg** [comment]
It works, but have some bugs.
1. If `pulseaudio-control-use-default-sink` is `t`, then I can't use `-select-sink-by-` functions anymore. If I understand correctly - they should change the sink, e.g. I should hear sound from another device.
2. If `pulseaudio-control-use-default-sink` is 'nil', then after `-select-sink-by-name` volume increase doesn't work.

**Comment by flexibeast** [comment]
Hmm.

Well, the *intent* of those functions, as i wrote them based on my understanding of the Pulse user documentation, was not to change where sound is output, but to change which sink to perform operations on (cf. the docstrings for those functions stating "Select which Pulse sink to act on ..."). i certainly might be misunderstanding things! However, when i run `pactl set-default-sink` directly from the command line, it doesn't seem to change where sound is output: i only have one sound card, but if i do e.g. `pactl set-default-sink rtp`, i don't lose audible sound from the sound card.

Is `set-default-sink` what you use on the command line to change where sound is output? If not, what do you use instead?

**Comment by sarg** [comment]
Yes, you are right. The `set-default-sink` will affect only new streams (https://askubuntu.com/questions/71863/how-to-change-pulseaudio-sink-with-pacmd-set-default-sink-during-playback#72076).

My setup is pretty simple - laptop with built-in speakers and bluetooth headphones. I use only one of them at any time. I expect that `pulseaudio-control` controls the currently running device without the need to manually specify which is it.

**Comment by flexibeast** [comment]
Ah okay, thank you for that.

So we can set aside item 1 in your list. However, item 2 is indeed a bug, and i've just pushed what i believe to be a fix for it - could you please test it and let me know if it works for you?

**Comment by sarg** [comment]
Nope, it doesn't. The problem is in
`pulseaudio-control--get-current-volume`, where you search-forward for
'Sink #'.
If I `-select-sink-by-name` then `--current-sink` is a name, not an index.

Also, you should match the end of line, otherwise 'Sink #19' and 'Sink #1'
will interfere. (real case, my bt headphones are registered as Sink #19)
```
Sink #19
        State: IDLE
        Name: bluez_sink.B8_AD_3E_42_00_34.a2dp_sink

```

**Comment by flexibeast** [comment]
> If I `-select-sink-by-name` then `--current-sink` is a name, not an index.

i don't observe that behaviour here; with the changes i pushed, `-select-sink-by-name` definitely sets `pulseaudio-control--current-sink` to an index, not a name. Do you observe the same behaviour if you run `pulseaudio-control` via `emacs -Q -l /path/to/pulseaudio-control.el`?

> Also, you should match the end of line, otherwise 'Sink #19' and 'Sink #1' will interfere.

Sorry, i'm not sure exactly which matching in the code you're referring to, here; can you direct me to it, please?

**Comment by flexibeast** [comment]
Oh also, you wrote above:

> I expect that pulseaudio-control controls the currently running device without the need to manually specify which is it.

Isn't that what we're adding support of `@DEFAULT_SINK@` for? Does setting `pulseaudio-control-use-default-sink` to `t` not give you this behaviour?

**Comment by sarg** [comment]
My bad. After `eval-buffer` everything works as expected.
The aforementioned line is https://github.com/flexibeast/pulseaudio-control/blob/support-default-sink/pulseaudio-control.el#L201

**Comment by flexibeast** [comment]
> My bad. After eval-buffer everything works as expected.

Ah good. :-)

> The aforementioned line is https://github.com/flexibeast/pulseaudio-control/blob/support-default-sink/pulseaudio-control.el#L201

Thanks. So, if `pulseaudio-control--current-sink` has been set to e.g. (as in your use-case) "19", that line should match "Sink #19", rather than "Sink #1". (i can't test that here, as i don't get a double-digit sink number when using my setup.) If it doesn't, `pulseaudio-control--current-index` must somehow be getting set to the wrong value somewhere - but i can't see where this might be happening. In `pulseaudio-control--get-default-sink`, on [line 178](https://github.com/flexibeast/pulseaudio-control/blob/support-default-sink/pulseaudio-control.el#L178), we have:

      (while (re-search-forward "\\([[:digit:]]+\\)\\s-+\\(\\S-+\\)" nil t)

and the `[[:digit:]]+` there is a greedy match which should match as many digits in a row as possible. Then, in `pulseaudio-control--get-sinks`, on [line 210](https://github.com/flexibeast/pulseaudio-control/blob/support-default-sink/pulseaudio-control.el#L210), we have:

      (let ((fields-re "^\\(\\S-+\\)\\s-+\\(\\S-+\\)")

and the `^\\(\\S-+\\)` there is a greedy match which should match as many non-whitespace characters from the start of the line as possible. Can you point me to the function which is trying to use sink "1" instead of "19"?

**Comment by sarg** [comment]
And you are right here too. Because an output of `pactl list sinks` is sorted you will get the correct match even if there are many lines with the desired prefix.

**Comment by flexibeast** [comment]
:-)

So, i'll wait to hear from @seblemaguer about whether this addresses issue #6 for them - if so, i'll merge the `support-default-sink` branch to `master`.

**Comment by sarg** [comment]
Found a small issue:
`pulseaudio-control-increase-volume` raises error when the volume is zero:
```
        Volume: front-left: 0 /   0% / -inf dB,   front-right: 0 /   0% / -inf dB
```
Seems that is caused by `-inf dB`

**Comment by flexibeast** [comment]
@sarg: As i've not heard from @seblemaguer in the last six months, i've decided to go ahead and merge the `support-default-sink` branch to `master`.

Are you still experiencing the error caused by `-inf dB`? If so, please open a new issue for it, and i'll try to address it as soon as i can.

**Pull request closed without merging**
