### PR TITLE
Add util function to set the current running sink

### PR DESCRIPTION
**Pull request by seblemaguer**
Hello,

that is more a base of discussion than a final solution :)

### CODE REVIEW

**Comment by flexibeast** [comment]
Firstly, thanks for wanting to contribute to the project!

i think i might have misunderstood what you're asking for; do the `pulseaudio-control-select-sink-by-index` and `pulseaudio-control-select-sink-by-name` commands not already do what you want?

EDIT: Oh wait, you're talking about functionality to make whatever PA sink is currently outputting audio to be the 'current' sink for `pulseaudio-control`? If so, yes, good idea. :-)

**Comment by seblemaguer** [comment]
yes the idea is to select the one which is currently outputting the audio to be the current sink. However, as you can see it needs to be done explicitly and I don't know if it is the best way to do it. That is why I said it is more to discuss about it :)


EDIT: it seems that it might solve #4

**Comment by seblemaguer** [comment]
Hello, is there any news about this PR?

**Comment by flexibeast** [comment]
My apologies - unfortunately, due to ongoing personal commitments (including some involving serious health issues), i've not been able to focus on my FOSS dev. i'll try to get back to it as soon as i can, but i'm not sure when that might be - sorry!

**Comment by seblemaguer** [comment]
no worries, that was just to be sure. It can wait so just get well soon :)

**Comment by sarg** [comment]
Hi there. Please take a look at #4. Mighty @ambrevar pointed that pactl has special `@DEFAULT_SINK@` index.

**Comment by seblemaguer** [comment]
@sarg thanks a lot. The solution of @Ambrevar is more elegant than mine.

**Comment by flexibeast** [comment]
@seblemaguer: i've just pushed what i believe to be a solution to this issue to [the `support-default-sink` branch](https://github.com/flexibeast/pulseaudio-control/tree/support-default-sink). Rather than the user having to manually set the internal variable `pulseaudio-control--current-sink` to achieve the desired result[1], they can instead utilise the defcustom `pulseaudio-control-use-default-sink` and/or the command ` pulseaudio-control-toggle-use-of-default-sink`. Could you please checkout that branch and let me know if it works for you?

[1] My comment [here](https://github.com/flexibeast/pulseaudio-control/pull/8#issuecomment-401331277) explains why i don't want to support this approach.

**Comment by seblemaguer** [comment]
@flexibeast hello, sure I do that asap :)

**Comment by flexibeast** [comment]
@seblemaguer: As i've not heard back from you in the last six months, i've decided to just go ahead and merge the `support-default-sink` branch to `master`; please let me know whether or not it solves your issue?

**Comment by seblemaguer** [comment]
Hello, yes sorry I go trapped in a "work black hole" and this pull request went out of my radar :/

yes it solves my issue :) I close this pull request as it is not useful anymore.

Sorry again

**Pull request closed without merging**
