### PR TITLE
Initial sink inputs support.

### PR DESCRIPTION
**Pull request by sarg**
Hi there.
I have implemented two internal functions:
1. pulseaudio-control--get-sink-inputs, which returns list of sink inputs (basically currently playing programs)
2. pulseaudio-control--set-sink-input-mute, which allows to toggle mute for a particular sink input

### CODE REVIEW

**Comment by flexibeast** [comment]
Thanks, this looks promising .... i take it you're working on the user-facing functions that make use of these functions?

**Comment by sarg** [comment]
Yes and no. I do have a function using those, but it isn't interactive. I am muting certain application using hotkey.

**Comment by flexibeast** [comment]
Okay, so could you please explain why `--set-sink-input-mute` needs to be an internal function, rather than an interactive function?

**Comment by sarg** [comment]
`--set-sink-input-mute` is internal because it'l be tedious to use without autocomplete as pulseaudio doesn't provide predictable IDs for sink inputs.

**Comment by flexibeast** [comment]
Merged - thanks!

**Pull request merged**
