### PR TITLE
Added mute status to display-volume

### PR DESCRIPTION
**Pull request by ellingtonsantos**

### CODE REVIEW

**Comment by flexibeast** [comment]
Looks good overall - thanks! One small thing:
    `"Get volume of currently-selected sink."`
i assume you meant:
    `"Get mute status of currently-selected sink."`
?

**Comment by ellingtonsantos** [comment]
Actually display-volume shows volume AND mute status.

**Comment by ellingtonsantos** [comment]
You were talking about pulseaudio-control--get-current-mute.

yes yes

you are right. lol

**Comment by flexibeast** [comment]
:-) Merged, thanks!

**Pull request merged**
